export const e2e = {
  targetId: "first-customer-browser-target",
  targetSlug: "first-customer-browser-target",
  targetName: "First Customer Browser Restaurant",
  existingId: "first-customer-browser-existing",
  existingSlug: "first-customer-browser-existing",
  existingName: "Existing Owner Workspace",
  unauthorizedId: "first-customer-browser-unauthorized",
  unauthorizedSlug: "first-customer-browser-unauthorized",
  unauthorizedName: "Unowned Browser Workspace",
  ownerEmail: "owner@restaurant.example.test",
  editedName: "First Customer Published Browser Edit",
  discoveryArticleSlug: "a-table-in-late-summer",
  discoveryArticleTitle: "A table in late summer",
  customHostname: "first-customer.example.test",
  foodId: "first-customer-browser-food-factory",
  foodSlug: "first-customer-browser-food-factory",
  foodName: "Factory Food Retail Browser Preview",
  foodOwnerEmail: "owner@example.com",
  foodSupersededInvitationToken: "food_superseded_claim_token_1234567890abcdef",
};
